<?php $this->layout($templateFolder . '::' . $layout, ['templateFolder' => $templateFolder, 'title' => $title, 'model' => $model]) ?>
<div class="row row-cols-<?= $cols ?>">
    <?php foreach ($components as $component): ?>
        <div class="col">
            <?php if ($component->hasTitle()): ?>
                <h3><?= $component->getTitle() ?></h3>
            <hr>
            <?php endif; ?>
            <?php $this->insert($templateFolder . '::' . $component->getTemplate(), ['templateFolder' => $templateFolder, 'component' => $component, 'fields' => $component->getFieldList(), 'model' => $component->getComponentModel()]) ?>
        </div>
    <?php endforeach ?>
</div>
<?php $this->push('javascript') ?>
<script lang="js">
    $().ready(function ($) {
        $body = $('body');
        $body.off('click').on('click', '.nav', function (event) {
            $.get(window.location, {
                navid: $(event.currentTarget).attr('id'),
                navindex: $(event.currentTarget).data('index')
            })
        });

        feather.replace()
    });
</script>
<?php $this->stop() ?>
