<?php
/**
 * @var Mvc\View\View $view
 */

/**
 * @var string $templateFolder
 */
?>
<?php $this->layout($templateFolder . '::' . $view->getLayout()) ?>
<div class="row row-cols-<?= $view->getCols() ?>">
    <?php foreach ($view->getComponentList() as $component): ?>
        <div class="col">
            <?php if ($component->hasTitle()): ?>
                <h3><?= $component->getTitle() ?></h3>
            <hr>
            <?php endif; ?>
            <?php $this->insert($templateFolder . '::' . $component->getTemplate(), ['component' => $component]) ?>
        </div>
    <?php endforeach; ?>
</div>
<?php $this->push('javascript') ?>
<script src="/js/jquery-3.5.1.min.js"></script>
<script src="/js/popper-1.16.1.min.js"></script>
<script src="/js/feather-4.28.0.min.js"></script>
<script src="/js/bs-custom-file-input-1.3.4.min.js"></script>
<script src="/js/bootstrap-4.5.3.min.js"></script>
<script lang="js">
    $().ready(function ($) {
        $body = $('body');
        $body.off('click.handleNavState').on('click.handleNavState', '.js-nav', function (event) {
            $.get(window.location, {
                navid: $(event.currentTarget).attr('id'),
                navindex: $(event.target).data('index')
            });
        });
        feather.replace()
    });
</script>
<?php $this->stop() ?>
<?php $this->push('stylesheets') ?>
<link rel="stylesheet" href="/css/bootstrap-4.5.3.min.css">
<?php $this->stop() ?>

