<?
/**
 * @var $component \Mvc\View\Components\Edit\Edit
 * @var $templateFolder string
 */
?>
<form method="post">
    <div class="row row-cols-1 row-cols-sm-<?= $component->getCols() ?>">
        <? $prevChapter = null ?>
        <? foreach ($component->getFieldList() as $key => $field): ?>
            <? if ($key == 0 || !$field->isAppendToPrevious()): ?>
                <div class="col">
            <? endif ?>
            <? if ($field->isShow($component->getBean())): ?>
                <?= $field->getChapter() != $prevChapter ? "<h4>{$field->getChapter()}</h4>" : '' ?>
                <? $this->insert($templateFolder . '::' . $field->getTemplate(), [
                    'field' => $field,
                    'bean' => $component->getBean(),
                    'errors' => $component->getValidationHelper()->getErrorList($field->getKey()),
                ]) ?>
            <? endif; ?>
            <? if ($key === count($component->getFieldList()) - 1 || !$component->getFieldList()[$key + 1]->isAppendToPrevious()): ?>
                </div>
            <? endif ?>
            <? $prevChapter = $field->getChapter() ?>
        <? endforeach ?>
    </div>
    <input type="hidden" name="token" value="<?= $token ?? '' ?>">
</form>
