<?
/**
 * @var $component \Mvc\View\Components\Base\AbstractComponent
 * @var $templateFolder string
 */
?>
<? foreach ($component->getBeanList() as $bean): ?>
    <div class="row row-cols-1 row-cols-sm-<?= $component->getCols() ?>">
        <? foreach ($component->getFieldList() as $field): ?>
            <div class="col">
                <? if ($field->isShow($bean)): ?>
                    <? $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $bean]) ?>
                <? endif; ?>
            </div>
        <? endforeach ?>
    </div>
<? endforeach ?>
