<div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="<?= $field->getKey() ?>" name="<?= $field->getKey() ?>"
           value="<?= $value ?>" <?= $field->isChecked() ? 'checked' : '' ?>>
    <label class="form-check-label" for="<?= $field->getKey() ?>"><?= $field->getName() ?></label>
    <small id="<?= $field->getKey() ?>__hint" class="form-text text-muted"><?= $field->getHint() ?></small>
</div>
