<div class="form-group">
    <label for="<?= $field->getKey($data) ?>"><?=$field->getName($data)?></label>
    <input type="<?= $field->getType($data) ?>"
           class="form-control"
           id="<?= $field->getKey($data) ?>"
           name="<?= $field->getKey($data) ?>"
           value="<?= $field->getValue($data) ?>"
           aria-describedby="<?= $field->getKey($data) ?>__hint"
        <?=$field->isRequired() ? ' required' : ''?>>
    <?php if ($field->hasHint($data)): ?>
        <small id="<?= $field->getKey($data) ?>__hint" class="form-text text-muted"><?= $field->getHint($data) ?></small>
    <?php endif; ?>
</div>
