<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<?= $description ?>">
    <meta name="author" content="<?= $author ?>">
    <title><?= $title . ' - ' . $model->getTitle()?></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet"/>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            font-size: .875rem;
        }

        .feather {
            width: 16px;
            height: 16px;
            vertical-align: text-bottom;
        }

        /*
         * Sidebar
         */

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100; /* Behind the navbar */
            padding: 48px 0 0; /* Height of navbar */
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        @media (max-width: 767.98px) {
            .sidebar {
                top: 5rem;
            }
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: .5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        @supports ((position: -webkit-sticky) or (position: sticky)) {
            .sidebar-sticky {
                position: -webkit-sticky;
                position: sticky;
            }
        }

        .sidebar .nav-link {
            font-weight: 500;
            color: #333;
        }

        .sidebar .nav-link .feather {
            margin-right: 4px;
            color: #999;
        }

        .sidebar .nav-link.active {
            color: #007bff;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
            color: inherit;
        }

        .sidebar-heading {
            font-size: .75rem;
            text-transform: uppercase;
        }

        /*
         * Navbar
         */

        .navbar-brand {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: 1rem;
            background-color: rgba(0, 0, 0, .25);
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
        }

        .navbar .navbar-toggler {
            top: .25rem;
            right: 1rem;
        }

        .navbar .form-control {
            padding: .75rem 1rem;
            border-width: 0;
            border-radius: 0;
        }

        .form-control-dark {
            color: #fff;
            background-color: rgba(255, 255, 255, .1);
            border-color: rgba(255, 255, 255, .1);
        }

        .form-control-dark:focus {
            border-color: transparent;
            box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
        }
    </style>
    <?= $this->section('stylesheets') ?>
</head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#"><?= $title ?></a>
    <?php if ($model->hasNavigation()): ?>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
                data-target="#sidebarNavigation" aria-controls="sidebarNavigation" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <?php endif ?>
    <?php if ($searchAction): ?>
        <form class="w-100" method="post" action="<?= $searchAction ?>">
            <input name="search" class="form-control form-control-dark w-100" type="text" placeholder="<?= $searchLabel ?>" aria-label="<?= $searchLabel ?>">
        </form>
    <?php endif ?>

    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="<?= $logoutLink ?>"><?= $logoutLabel ?></a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <?php if ($model->hasNavigation()): ?>
            <nav id="sidebarNavigation" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <?php foreach ($model->getNavigationList() as $navigation): ?>
                        <?php if ($navigation->hasTitle()): ?>
                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                                <span><?= $navigation->getTitle() ?></span>
                                <?php if ($navigation->hasAction()): ?>
                                    <?php if ($navigation->getAction()->hasLink()): ?>
                                        <a class="d-flex align-items-center text-muted"
                                           href="<?= $navigation->getAction()->getLink() ?>"
                                           aria-label="<?= $navigation->getAction()->hasName() ? $navigation->getAction()->getName() : '' ?>">
                                            <?php if ($navigation->getAction()->hasIcon()): ?>
                                                <span data-feather="<?= $navigation->getAction()->getIcon() ?>"></span>
                                            <?php endif ?>
                                        </a>
                                    <?php endif ?>
                                <?php endif ?>
                            </h6>
                        <?php endif ?>
                        <ul class="nav flex-column mb-2">
                            <?php foreach ($navigation->getElementList() as $element): ?>
                                <li class="nav-item">
                                    <a class="nav-link <?= $element->isActive() ? 'active' : '' ?>"
                                       href="<?= $element->getLink() ?>">
                                        <?php if ($element->hasIcon()): ?>
                                            <span data-feather="<?= $element->getIcon() ?>"></span>
                                        <?php endif ?>
                                        <?= $element->getName() ?>
                                        <?php if ($element->isActive()): ?>
                                            <span class="sr-only">(current)</span>
                                        <?php endif ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endforeach ?>
                </div>
            </nav>
        <?php endif ?>
        <main role="main" class="col-md-9 <?= $model->hasNavigation() ? 'ml-sm-auto' : 'm-auto'?> col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2"><?= $model->getTitle() ?></h1>
                <?php if ($model->hasToolbar()): ?>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group mr-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>
                <?php endif ?>
            </div>
            <?= $this->section('content') ?>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<?= $this->section('javascript') ?>
</html>
