<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title><?= $this->e($title) ?></title>
    <link rel="shortcut icon" href="favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet"/>
    <style>
        body {
            padding-top: 70px;
        }

        .app {
            min-height: 100vh;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin: -.5rem 0;
            filter: brightness(0) invert(1);
        }
    </style>
    <?= $this->section('stylesheets') ?>
</head>
<body class="app">
<header class="app-header">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <?php if ($model->hasMenu()): ?>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse"
                            aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <?php endif ?>
                <?php if ($model->hasBrand()): ?>

                    <!-- Brand -->
                    <a class="navbar-brand" href="<?= $model->getBrand()['link'] ?>">
                        <img src="<?= $model->getBrand()['icon'] ?>" alt="<?= $model->getBrand()['name'] ?>"
                             height="<?= $model->getBrand()['height'] ?>"/>
                    </a>
                <?php endif ?>

            </div>
            <!-- Links -->
            <?php if ($model->hasMenu()): ?>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <?php foreach ($model->getMenu() as $item): ?>
                            <li class="nav-item">
                                <a href="<?= $item['link'] ?>" target="_self" class="nav-link"><?= $item['name'] ?></a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            <?php endif ?>
        </div>
    </nav>
</header>

<h1><?= $title ?></h1>

<div class="app-content">
    <main class="container">
        <?= $this->section('content') ?>
    </main>
</div>

<footer class="app-footer">
    <div class="container">
        <hr/>
        <?php if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <?php else: ?>
            <p>
                &copy; <?= date('Y') ?> <a href="https://kleinschuster.de">Robert Kleinschuster</a>
            </p>
        <?php endif ?>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<?= $this->section('javascript') ?>
</body>
</html>
