<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title><?= $title . ' - ' . $model->getTitle()?></title>
    <link rel="shortcut icon" href="favicon.ico"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet"/>
    <style>
        body {
            padding-top: 70px;
        }

        .app {
            min-height: 100vh;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin: -.5rem 0;
            filter: brightness(0) invert(1);
        }
    </style>
    <?= $this->section('stylesheets') ?>
</head>
<body class="app">

<h1 class="text-center mx-auto"><?= $title ?></h1>
<hr>
<h2 class="text-center mx-auto"><?= $model->getTitle() ?></h2>

<div class="app-content">
    <main class="container">
        <?= $this->section('content') ?>
    </main>
</div>

<footer class="app-footer">
    <div class="container">
        <hr/>
        <?php if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <?php else: ?>
            <p>
                &copy; <?= date('Y') ?> <a href="https://kleinschuster.de">Robert Kleinschuster</a>
            </p>
        <?php endif ?>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<?= $this->section('javascript') ?>
</body>
</html>
