<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title><?= $title . ' - ' . $model->getTitle() ?></title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
        .form-signin .checkbox {
            font-weight: 400;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }


        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <?= $this->section('stylesheets') ?>
</head>
<body class="text-center">
<form class="form-signin">
    <h1 class="text-center mx-auto"><?= $title ?></h1>
    <hr>
    <h2 class="text-center mx-auto mb-5"><?= $model->getTitle() ?></h2>
    <?= $this->section('content') ?>
</form>

<footer class="app-footer">
    <div class="container">
        <hr/>
        <?php if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <?php else: ?>
            <p>
                &copy; <?= date('Y') ?> <a href="https://kleinschuster.de">Robert Kleinschuster</a>
            </p>
        <?php endif ?>
    </div>
</footer>
<?= $this->section('javascript') ?>
</body>
</html>
