<?
/**
 * @var Mvc\View\View $view
 * @var string $templateFolder
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <? if ($view->hasData('description')): ?>
        <meta name="description" content="<?= $view->getData('description') ?>">
    <? endif; ?>
    <? if ($view->hasData('author')): ?>
        <meta name="author" content="<?= $view->getData('author') ?>">
    <? endif; ?>
    <? if ($view->hasData('title')): ?>
        <title><?= $view->getData('title') ?></title>
    <? endif; ?>
    <? if ($view->hasData('favicon')): ?>
        <link rel="shortcut icon" href="<?= $view->getData('favicon') ?>"/>
    <? else: ?>
        <link rel="shortcut icon" href="favicon.ico"/>
    <? endif; ?>
    <?= $this->section('stylesheets') ?>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }


        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body class="text-center">
<form class="form-signin">
    <? if ($view->hasData('title')): ?>
        <h1 class="text-center mx-auto"><?= $view->getData('title') ?></h1>
    <? endif; ?>
    <? if ($view->hasData('heading')): ?>
        <hr>
        <h2 class="text-center mx-auto mb-5"><?= $view->getData('heading') ?></h2>
    <? endif; ?>

    <?= $this->section('content') ?>
</form>

<footer class="app-footer">
    <div class="container">
        <hr/>
        <? if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <? else: ?>
            <p>
                &copy; <?= date('Y') ?> <a href="https://kleinschuster.de">Robert Kleinschuster</a>
            </p>
        <? endif ?>
    </div>
</footer>
<?= $this->section('javascript') ?>
</body>
</html>
