<div class="col">
    <table class="table table-striped table-hover table-bordered table-sm">
        <thead class="bg-light">
        <tr>
            <?php foreach ($fields as $key => $field): ?>
                <td><?= $field->getName() ?></td>
            <?php endforeach ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($model->getComponentDataBeanList() as $bean): ?>
            <tr>
                <?php foreach ($fields as $field): ?>
                    <td>
                        <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    </td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
