<div class="col">
    <table class="table table-striped table-hover table-bordered table-sm">
        <thead class="bg-light">
        <tr>
            <?php foreach ($fields as $key => $field): ?>
                <td><?= $field->getName() ?></td>
            <?php endforeach ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($model->getComponentDataBeanList() as $bean): ?>
            <tr>
                <?php $previousChapter = null?>
                <?php foreach ($fields as $field): ?>
                    <?php if ($field->getChapter() == $previousChapter): ?>
                        <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php elseif ($previousChapter == null): ?>
                        <td>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php else: ?>
                        </td>
                        <td>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php endif;?>
                    <?php $previousChapter = $field->getChapter()?>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
