<h3><?= $component->getTitle() ?></h3>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered table-sm ">
        <thead class="bg-light">
        <tr>
            <?php $previousChapter = null?>
            <?php $index = 1?>
            <?php $count = count($fields)?>
            <?php foreach ($fields as $key => $field): ?>
                <?php if ($field->getChapter() == $previousChapter): ?>
                    <?= $field->getName() ?>
                <?php elseif ($previousChapter == null): ?>
                    <td>
                    <?= $field->getName() ?>
                <?php else: ?>
                    </td>
                    <td>
                    <?= $field->getName() ?>
                <?php endif;?>
                <?php if ($index == $count): ?>
                    </td>
                <?php endif;?>
                <?php $previousChapter = $field->getChapter()?>
                <?php $index++;?>
            <?php endforeach ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($model->getComponentDataBeanList() as $bean): ?>
            <tr>
                <?php $previousChapter = null?>
                <?php $index = 1?>
                <?php $count = count($fields)?>
                <?php foreach ($fields as $field): ?>
                    <?php if ($field->getChapter() == $previousChapter): ?>
                        <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php elseif ($previousChapter == null): ?>
                        <td <?= $field->hasWidth() ? 'style="width: ' . $field->getWidth() . 'px"': ''?>>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php else: ?>
                        </td>
                        <td <?= $field->hasWidth() ? 'style="width: ' . $field->getWidth() . 'px"': ''?>>
                            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
                    <?php endif;?>
                    <?php if ($index == $count): ?>
                        </td>
                    <?php endif;?>
                    <?php $previousChapter = $field->getChapter()?>
                    <?php $index++;?>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
