<div class="alert alert-<?= $component->getStyle() ?>" role="alert">
    <h4 class="alert-heading"><?= $component->getTitle() ?></h4>
    <?php foreach ($model->getComponentDataBeanList() as $bean): ?>
        <?php foreach ($fields as $key => $field): ?>
            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['templateFolder' => $templateFolder, 'field' => $field, 'data' => $bean]) ?>
            <?= count($fields) > 1 && $key < count($fields) - 1 ? '<hr>' : '' ?>
        <?php endforeach ?>
    <?php endforeach ?>
</div>
