<?php
/**
 * @var $component \Mvc\View\Components\Toolbar\Toolbar
 * @var $templateFolder string
 */
?>
<div class="btn-toolbar mb-2">
    <?php foreach ($component->getFieldList() as $key => $field): ?>
        <?php if ($key == 0 || !$field->isAppendToPrevious()): ?>
            <div class="<?= (count($fields) > 1) ? 'btn-group ' : '' ?>mr-1">
        <?php endif ?>
        <?php if ($field->isShow($component->getBean())): ?>
            <?php $this->insert($templateFolder . '::' . $field->getTemplate(), ['field' => $field, 'bean' => $component->getBean()]) ?>
        <?php endif; ?>
        <?php if ($key === count($fields) - 1 || !$fields[$key + 1]->isAppendToPrevious()): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
</div>
