<?php if ($field->hasAction()): ?>
    <a href="<?= $field->getAction($data) ?>"
       class="badge<?= $field->hasStyle() ? ' badge-' . $field->getStyle() : '' ?><?= $field->hasType() ? ' badge-' . $field->getType() : '' ?>"><?= $field->getValue($data) ?></a>
<?php else: ?>
    <span class="badge<?= $field->hasStyle() ? ' badge-' . $field->getStyle() : '' ?><?= $field->hasType() ? ' badge-' . $field->getType() : '' ?>"><?= $field->getValue($data) ?></span>
<?php endif; ?>
