<?php

/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractBadge
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 */
?>
<?php if ($field->hasAction()): ?>
    <a href="<?= $field->getAction($bean) ?>"
       class="badge<?= $field->hasStyle() ? ' badge-' . $field->getStyle() : '' ?><?= $field->hasType() ? ' badge-' . $field->getType() : '' ?>"><?= $field->getValue($bean) ?></a>
<?php else: ?>
    <span class="badge<?= $field->hasStyle() ? ' badge-' . $field->getStyle() : '' ?><?= $field->hasType() ? ' badge-' . $field->getType() : '' ?>"><?= $field->getValue($bean) ?></span>
<?php endif; ?>
