<?
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractBlockquote
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 */
?>
<blockquote class="blockquote<?= $field->hasAlign() ? ' text-' . $field->getAlign() : '' ?>">
    <p class="mb-0"><?= $field->getValue($bean) ?></p>
    <? if ($field->hasFooter()): ?>
        <footer class="blockquote-footer"><?= $field->getFooter() ?>
            <? if ($field->hasSource()): ?>
                <cite title="<?= $field->getSource() ?>"><?= $field->getSource() ?></cite>
            <? endif; ?>
        </footer>
    <? endif; ?>
</blockquote>
