<div class="form-group form-check">
    <input type="checkbox" class="form-check-input"
           id="<?= $field->getKey($data) ?>"
           name="<?= $field->getKey($data) ?>"
           value="<?= $field->getValue($data) ?>"
        <?= $field->isChecked($data) ? 'checked' : '' ?>>
    <label class="form-check-label" for="<?= $field->getKey($data) ?>"><?= $field->getName($data) ?></label>
    <?php if ($field->hasHint()): ?>
        <small id="<?= $field->getKey($data) ?>__hint"
               class="form-text text-muted"><?= $field->getHint($data) ?></small>
    <?php endif; ?>
</div>
