<?
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractCheckbox
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 * @var $errors array
 */
?>
<div class="form-group form-check">
    <input type="checkbox" class="form-check-input <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
           id="<?= $field->getKey() ?>"
           name="<?= $field->getKey() ?>"
           value="<?= $field->getValue($bean) ?>"
        <?=$field->isRequired() ? ' required' : ''?>
        <?= $field->isChecked() ? ' checked' : '' ?>>
    <? if ($field->hasTitle()): ?>
        <label class="form-check-label" for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <? endif;?>
    <? if (is_array($errors)): ?>
        <? foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <? endforeach ?>
    <? endif ?>
    <? if ($field->hasHint()): ?>
        <small id="<?= $field->getKey() ?>__hint"
               class="form-text text-muted"><?= $field->getHint() ?></small>
    <? endif; ?>
</div>
