<?php if ($field->hasSource($data)): ?>
    <?php if ($field->hasAlign($data) && $field->getAlign($field) == \Mezzio\Mvc\View\Components\Base\Fields\AbstractText::ALIGN_CENTER): ?>
        <img
                src="<?= $field->getSource($data) ?>"
                class="<?= $field->hasSize($data) ? 'img-' . $field->getSize($field) : '' ?> mx-auto d-block"
                alt="<?= $field->getValue($data) ?>">
    <?php else: ?>
        <img
                src="<?= $field->getSource($data) ?>"
                class="<?= $field->hasSize($data) ? 'img-' . $field->getSize($field) : '' ?>
               <?= $field->hasAlign($data) ? ' float-' . $field->getAlign($field) : '' ?>"
                alt="<?= $field->getValue($data) ?>">
    <?php endif; ?>
<?php endif; ?>
