<?
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractLink
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 */
?>
<a <?= $field->hasLink() ? " href=\"{$field->getLink($bean)}\"" : '' ?> <?= $field->hasTarget() ? " target=\"{$field->getTarget()}\"" : '' ?>
class="<?=$field->getClass()?>">
    <? if($field->hasIcon()): ?>
        <span data-feather="<?=$field->getIcon()?>"></span>
    <? endif;?>
    <?= $field->getValue($bean) ?>
</a>
