<div class="form-group">
    <label for="<?= $field->getKey($data) ?>"><?= $field->getName($data) ?></label>
    <select class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
            id="<?= $field->getKey($data) ?>"
            name="<?= $field->getKey($data) ?>"
            size="<?= $field->getSize($data) ?>"
        <?=$field->isRequired() ? ' required' : ''?>
        <?= $field->isMultiple($data) ? ' multiple' : '' ?>>
        <?php foreach ($field->getSelectOptions($data) as $value => $name): ?>
            <option
                <?= $field->getValue($data) == $value ? ' selected' : '' ?>value="<?= $value ?>"><?= $name ?></option>
        <?php endforeach; ?>
    </select>
    <?php if (is_array($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey($data) ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
