<?
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractSelect
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 * @var $errors array
 */
?>
<div class="form-group">
    <? if ($field->hasTitle()): ?>
        <label for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <? endif; ?>
    <select class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
            id="<?= $field->getKey() ?>"
            name="<?= $field->getKey() ?>"
            size="<?= $field->getSize() ?>"
        <?= $field->isRequired() ? ' required' : '' ?>
        <?= $field->isMultiple() ? ' multiple' : '' ?>>
        <? foreach ($field->getSelectOptions() as $value => $name): ?>
            <option
                <?= $field->getValue($bean) == $value ? ' selected' : '' ?>value="<?= $value ?>"><?= $name ?></option>
        <? endforeach; ?>
    </select>
    <? if (is_array($errors)): ?>
        <? foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <? endforeach ?>
    <? endif ?>
</div>
