<?
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractTextarea
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 * @var $errors array
 */
?>
<div class="form-group">
    <? if ($field->hasTitle()): ?>
        <label for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <? endif; ?>
    <textarea class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
              id="<?= $field->getKey() ?>"
              name="<?= $field->getKey() ?>"
              <?= $field->isRequired() ? ' required' : '' ?>
        <?= $field->hasRows() ? " rows=\"{$field->getRows()}\"" : '' ?>>
        <?= $field->getValue($bean) ?>
    </textarea>
    <? if (is_array($errors)): ?>
        <? foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <? endforeach ?>
    <? endif ?>
</div>
