<div class="form-group">
    <label for="<?= $field->getKey($data) ?>"><?= $field->getName($data) ?></label>
    <textarea class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
              id="<?= $field->getKey($data) ?>"
              name="<?= $field->getKey($data) ?>"
              <?=$field->isRequired() ? ' required' : ''?>
        <?= $field->hasRows($data) ? " rows=\"{$field->getRows($data)}\"" : '' ?>>
        <?=$field->getValue($data)?>
    </textarea>
    <?php if (is_array($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey($data) ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
