<?php
/**
 * @var $field \Mvc\View\Components\Base\Fields\AbstractTextarea
 * @var $bean \NiceshopsDev\Bean\BeanInterface
 * @var $errors array
 */
?>

<div class="form-group">
    <?php if ($field->hasTitle()): ?>
        <label for="<?= $field->getKey() ?>"><?= $field->getTitle() ?></label>
    <?php endif; ?>
    <textarea class="form-control <?= is_array($errors) && count($errors) ? ' is-invalid ' : '' ?>"
              id="<?= $field->getKey() ?>"
              name="<?= $field->getKey() ?>"
        <?= $field->isRequired() ? ' required' : '' ?>
        <?= $field->hasRows() ? " rows=\"{$field->getRows()}\" " : '' ?>><?= $field->getValue($bean) ?></textarea>
    <div id="edit-<?= $field->getKey() ?>">
        <?= $field->getValue($bean) ?>
    </div>
    <?php if (is_array($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <div id="<?= $field->getKey() ?>_Error" class="invalid-feedback">
                <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function(event) {
        var textarea = document.getElementById('<?= $field->getKey() ?>');
        var x = textarea.getAttribute('class')
        document.getElementById('<?= $field->getKey() ?>').setAttribute('class', x + ' d-none');

        var quill = new Quill('#edit-<?= $field->getKey() ?>', {
            modules: {
                toolbar: [
                    [{ header: [1, 2, 3, 4, 5, 6,  false] }],
                    ['bold', 'italic', 'underline','strike'],
                    ['image', 'code-block'],
                    ['link'],
                    [{ 'script': 'sub'}, { 'script': 'super' }],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    ['clean']
                ]
            },
            theme: 'snow'
        });
        quill.on('text-change', function(delta, oldDelta, source) {
            document.getElementById('<?= $field->getKey() ?>').innerText = quill.root.innerHTML;
        });
    });
</script>
